# CrowdSec Config
crowdsec_lapi_url: http://localhost:8080/
crowdsec_lapi_key: ${LAPI_KEY}
crowdsec_update_frequency: -1s


cloudflare_config:
  accounts:
  - id: ${CF_ACC_ID}
    token: ${CF_TOKEN} 
    ip_list_prefix: crowdsec
    zones:
    - remediation: block
      zone_id: ${CF_ZONE_ID} 

  update_frequency: blah

# Bouncer Config
daemon: false
log_mode: stdout
log_dir: /var/log/
log_level: info